// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhcdugrwubgzntrqchpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoY2R1Z3J3dWJnem50cnFjaHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDI0MTksImV4cCI6MjA3MzQxODQxOX0.KDiPNal4QZcP2_3pDHSta-YS_agR-uh733Tz3blkkHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});